#!/bin/sh

FILE=/var/lib/munin-node/plugin-state/dw.state
IFS=:

if [ "$#" -eq "1" ] && [ "$1" = "config" ]; then
cat <<'EOF'
graph_title Temperatur Boiler
graph_category Aerosmart
graph_vlabel Temperatur Boiler
graph_args --base 1000 --lower-limit 0 --units-exponent 0
graph_scale no
graph_order boilertemp boilerwaermepumpetemp boilerverdampfregistertemp
boilertemp.label Temperatur Boiler
boilertemp.draw LINE3
boilertemp.colour c53030
boilertemp.warning 30:58
boilertemp.critical 20:80
boilerwaermepumpetemp.label Temperatur Waermepumpe
boilerwaermepumpetemp.draw LINE2
boilerwaermepumpetemp.colour 45b46a
boilerverdampfregistertemp.label Temperatur Verdampfregister
boilerverdampfregistertemp.draw LINE2
boilerverdampfregistertemp.colour eac530
EOF
else
    if [ -f $FILE ] && [ -r $FILE ]; then
        grep boiler /var/lib/munin-node/plugin-state/dw.state
        unset IFS
    else
        echo "File not found!"
        exit 1
    fi
fi

